### ISSUE TITLE
OGCGeometry#convexHull returns incorrect results for points on a single line

### ISSUE THREAD

**Issue by mbasmanova** [Esri/geometry-api-java#172]
I'm seeing `convexHull` method returning incorrect results for some inputs:

* fails if input geometry is empty, but I expect to get empty geometry back
* returns empty geometry if input is a single point, but I expect to get the original point back
* returns *corrupt* geometry if all points are on the same line, but I expect to get a LINESTRING geometry back
* fails if input is a geometry collection where some of the geometries are empty

For `MULTIPOINT (1 1, 2 2)` input, the output is *corrupt*:

```
com.esri.core.geometry.GeometryException: corrupted geometry

	at com.esri.core.geometry.OperatorExportToWktLocal.exportPolygonToWkt(OperatorExportToWktLocal.java:111)
	at com.esri.core.geometry.OperatorExportToWktLocal.exportToWkt(OperatorExportToWktLocal.java:47)
	at com.esri.core.geometry.OperatorExportToWktLocal.execute(OperatorExportToWktLocal.java:31)
	at com.esri.core.geometry.GeometryEngine.geometryToWkt(GeometryEngine.java:274)
	at com.esri.core.geometry.ogc.OGCMultiPolygon.asText(OGCMultiPolygon.java:53)
```

Here is the error for empty geometry.

```
com.esri.core.geometry.GeometryException: This operation should not be performed on an empty geometry.

	at com.esri.core.geometry.Point.getXY(Point.java:102)
	at com.esri.core.geometry.ConvexHull.addPoint_(ConvexHull.java:375)
	at com.esri.core.geometry.ConvexHull.addGeometry(ConvexHull.java:68)
	at com.esri.core.geometry.OperatorConvexHullCursor.calculateConvexHullMerging_(OperatorConvexHullCursor.java:79)
	at com.esri.core.geometry.OperatorConvexHullCursor.next(OperatorConvexHullCursor.java:49)
	at com.esri.core.geometry.ogc.OGCGeometry.createFromEsriCursor(OGCGeometry.java:512)
	at com.esri.core.geometry.ogc.OGCGeometry.createFromEsriCursor(OGCGeometry.java:505)
	at com.esri.core.geometry.ogc.OGCGeometry.convexHull(OGCGeometry.java:448)
```

CC: @tpeng-fb

**Comment by stolstov** [comment]
@mbasmanova Could you check this branch, see if the issue is fixed?
https://github.com/Esri/geometry-api-java/tree/stolstov/issue_172

**Comment by mbasmanova** [comment]
@stolstov Sergey, thanks for authoring a fix. Looks like the corner cases I saw issues with are addressed. Here is the test that I ran.

```
public class TestOGCConvexHull
{
    @Test
    public void testPoint()
    {
        assertConvexHull("POINT EMPTY", "POINT EMPTY");
        assertConvexHull("POINT (1 2)", "POINT (1 2)");
    }

    @Test
    public void testMultiPoint()
    {
        assertConvexHull("MULTIPOINT EMPTY", "POINT EMPTY");
        assertConvexHull("MULTIPOINT (1 1, 2 2)", "LINESTRING (1 1, 2 2)");
    }

    @Test
    public void testGeometryCollection()
    {
        assertConvexHull("GEOMETRYCOLLECTION EMPTY", "POINT EMPTY");
        assertConvexHull("GEOMETRYCOLLECTION (MULTIPOINT (1 1, 2 2), POINT EMPTY)", "LINESTRING (1 1, 2 2)");
    }

    private static void assertConvexHull(String wkt, String expectedWkt)
    {
        OGCGeometry geometry = OGCGeometry.fromText(wkt);
        OGCGeometry convexHull = geometry.convexHull();
        Assert.assertEquals(convexHull.asText(), expectedWkt);
    }
}
```

**Comment by stolstov** [comment]
@mbasmanova Thank you, I have added a test for this in my branch.

**Comment by stolstov** [comment]
@mbasmanova Yes, sure. Do you have more bugs to find :)?
@randallwhitman Would need to do a minor release.

**Comment by mbasmanova** [comment]
@randallwhitman @stolstov Randall, Sergey, do you have an approximate timeline for the 2.1.1 release?

**Comment by randallwhitman** [comment]
Need to merge the branch for this before releasing.
Also, rather than a 2.1.1 I'd release 2.2.0 with Centroid and this one.

**Comment by stolstov** [comment]
@mbasmanova could you verify this?

**Comment by mbasmanova** [comment]
@stolstov Sergey, I ran my test on master and it passed. Thank you!
