### ISSUE TITLE
OGCGeometry#boundary fails with NullPointerException on empty linestring

### ISSUE THREAD

**Issue by mbasmanova** [Esri/geometry-api-java#173]
`OGCGeometry.fromText("LINESTRING EMPTY").boundary()` throws `NullPointerException`

```
java.lang.NullPointerException
	at com.esri.core.geometry.MultiPathImpl.isClosedPath(MultiPathImpl.java:568)
	at com.esri.core.geometry.MultiPathImpl.isClosedPathInXYPlane(MultiPathImpl.java:572)
	at com.esri.core.geometry.MultiPath.isClosedPathInXYPlane(MultiPath.java:673)
	at com.esri.core.geometry.ogc.OGCLineString.isClosed(OGCLineString.java:85)
	at com.esri.core.geometry.ogc.OGCCurve.boundary(OGCCurve.java:44)
```

**Comment by stolstov** [comment]
I've installed a fix for this into this branch:
https://github.com/Esri/geometry-api-java/tree/stolstov/issue_172

**Comment by stolstov** [comment]
@mbasmanova Could you verify this?

**Comment by mbasmanova** [comment]
@stolstov Sergey, I tried `OGCGeometry.fromText("LINESTRING EMPTY").boundary()` and it no longer fails, but returns `OGCMultiPoint: MULTIPOINT EMPTY`. Thank you!
